package concurrent;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import java.io.*;
import java.util.*;

public class GraphStats extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		RunTime.receivedMessage();
		GraphStats instance = (GraphStats)new GraphStats(uan, ual,null).construct();
		gc.WeakReference instanceRef=new gc.WeakReference(uan,ual);
		{
			Object[] _arguments = { args };

			//preAct() for local actor creation
			//act() for remote actor creation
			if (ual != null && !ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {instance.send( new Message(instanceRef, instanceRef, "act", _arguments, false) );}
			else {instance.send( new Message(instanceRef, instanceRef, "preAct", _arguments, false) );}
		}
		RunTime.finishedProcessingMessage();
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new GraphStats(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return GraphStats.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new GraphStats(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return GraphStats.getReferenceByLocation(new UAL(ual)); }
	public GraphStats(boolean o, UAN __uan)	{ super(false,__uan); }
	public GraphStats(boolean o, UAL __ual)	{ super(false,__ual); }
	public GraphStats(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null, sourceActor); }
	public GraphStats(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual, sourceActor); }
	public GraphStats(UniversalActor.State sourceActor)		{ this(null, null, sourceActor);  }
	public GraphStats()		{  }
	public GraphStats(UAN __uan, UAL __ual, Object obj) {
		//decide the type of sourceActor
		//if obj is null, the actor must be the startup actor.
		//if obj is an actorReference, this actor is created by a remote actor

		if (obj instanceof UniversalActor.State || obj==null) {
			  UniversalActor.State sourceActor;
			  if (obj!=null) { sourceActor=(UniversalActor.State) obj;}
			  else {sourceActor=null;}

			  //remote creation message sent to a remote system service.
			  if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			    WeakReference sourceRef;
			    if (sourceActor!=null && sourceActor.getUAL() != null) {sourceRef = new WeakReference(sourceActor.getUAN(),sourceActor.getUAL());}
			    else {sourceRef = null;}
			    if (sourceActor != null) {
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual!=null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());
			      activateGC();
			    }
			    createRemotely(__uan, __ual, "concurrent.GraphStats", sourceRef);
			  }

			  // local creation
			  else {
			    State state = new State(__uan, __ual);

			    //assume the reference is weak
			    muteGC();

			    //the source actor is  the startup actor
			    if (sourceActor == null) {
			      state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			    }

			    //the souce actor is a normal actor
			    else if (sourceActor instanceof UniversalActor.State) {

			      // this reference is part of garbage collection
			      activateGC();

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());

			      /* Garbage collection registration:
			       * register 'this reference' in sourceActor's forward list @
			       * register 'this reference' in the forward acquaintance's inverse list
			       */
			      String inverseRefString=null;
			      if (sourceActor.getUAN()!=null) {inverseRefString=sourceActor.getUAN().toString();}
			      else if (sourceActor.getUAL()!=null) {inverseRefString=sourceActor.getUAL().toString();}
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual != null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}
			      else {sourceActor.getActorMemory().getForwardList().putReference(state.getUAL());}

			      //put the inverse reference information in the actormemory
			      if (inverseRefString!=null) state.getActorMemory().getInverseList().putInverseReference(inverseRefString);
			    }
			    state.updateSelf(this);
			    ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			    if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
			  }
		}

		//creation invoked by a remote message
		else if (obj instanceof ActorReference) {
			  ActorReference sourceRef= (ActorReference) obj;
			  State state = new State(__uan, __ual);
			  muteGC();
			  state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			  if (sourceRef.getUAN() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAN());}
			  else if (sourceRef.getUAL() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAL());}
			  state.updateSelf(this);
			  ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(),state);
			  if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State {
		public GraphStats self;
		public void updateSelf(ActorReference actorReference) {
			((GraphStats)actorReference).setUAL(getUAL());
			((GraphStats)actorReference).setUAN(getUAN());
			self = new GraphStats(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.activateGC();
		}

		public void preAct(String[] arguments) {
			getActorMemory().getInverseList().removeInverseReference("rmsp://me",1);
			{
				Object[] __args={arguments};
				self.send( new Message(self,self, "act", __args, null,null,false) );
			}
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "concurrent.GraphStats$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		String inputFile = "input.txt";
		List Actors = new ArrayList();
		String outputFileA;
		String outputFileB;
		public List combinePartionsAnswerA_better(List t, List current) {
			Map current_counts;
			Map current_degrees;
			List BigMoney = new ArrayList();
			Map counts = new HashMap();
			Map degrees = new HashMap();
			current_counts = new HashMap();
			current_degrees = new HashMap();
			Map color_to_count = (Map)t.get(0);
			Map color_to_degree = (Map)t.get(1);
			Set colors = (Set)color_to_count.keySet();
			Iterator itr = colors.iterator();
			while (itr.hasNext()) {
				String color = (String)itr.next();
				int c_at_itr = (int)color_to_count.get(color);
				int d_at_itr = (int)color_to_degree.get(color);
				if (current_counts.containsKey(color)) {{
					int c = (int)current_counts.get(color);
					int d = (int)current_degrees.get(color);
					counts.put(color, c+c_at_itr);
					degrees.put(color, d+d_at_itr);
				}
}				else {{
					counts.put(color, c_at_itr);
					degrees.put(color, d_at_itr);
				}
}			}
			BigMoney.add(counts);
			BigMoney.add(degrees);
			{
				// standardOutput<-println("AAAAAA")
				{
					Object _arguments[] = { "AAAAAA" };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
			return BigMoney;
		}
		public void merge(Object[] results) {
			List BigMoney = new ArrayList();
			Map counts = new HashMap();
			Map degrees = new HashMap();
			for (int i = 0; i<results.length; ++i){
				List r = (List)results[i];
				Map curr_counts = (Map)r.get(0);
				Map curr_degrees = (Map)r.get(1);
				Set current_colors = (Set)curr_counts.keySet();
				Iterator itr = current_colors.iterator();
				while (itr.hasNext()) {
					String color = (String)itr.next();
					int c_at_itr = (int)curr_counts.get(color);
					int d_at_itr = (int)curr_degrees.get(color);
					if (counts.containsKey(color)) {{
						int c = (int)counts.get(color);
						int d = (int)degrees.get(color);
						counts.put(color, c+c_at_itr);
						degrees.put(color, d+d_at_itr);
					}
}					else {{
						counts.put(color, c_at_itr);
						degrees.put(color, d_at_itr);
					}
}				}
				{
					// standardOutput<-println(curr_counts)
					{
						Object _arguments[] = { curr_counts };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				{
					// standardOutput<-println(curr_degrees)
					{
						Object _arguments[] = { curr_degrees };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				{
					// standardOutput<-println()
					{
						Object _arguments[] = {  };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
			BigMoney.add(counts);
			BigMoney.add(degrees);
			{
				// standardOutput<-println(BigMoney)
				{
					Object _arguments[] = { BigMoney };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
		}
		public void act(String[] args) {
			Vector LinesInFile = new Vector();
			String line;
			try {
				BufferedReader in = new BufferedReader(new FileReader(inputFile));
				while ((line=in.readLine())!=null) {
					LinesInFile.add(line);
				}
				in.close();
			}
			catch (IOException ioe) {
				{
					// standardError<-println("[error] can't open file")
					{
						Object _arguments[] = { "[error] can't open file" };
						Message message = new Message( self, standardError, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
			}

			int a = 0;
			List NodeList = new ArrayList();
			List ColorList = new ArrayList();
			List EdgeList = new ArrayList();
			for (int i = 0; i<LinesInFile.size(); i++){
				if (i%4==0) {{
					String s = (String)LinesInFile.get(i);
					int act = (int)Integer.parseInt((String)s.split(" ")[1]);
					a = act;
				}
}				else {if (i%4==1) {{
					String Line = (String)LinesInFile.get(i);
					NodeList = Arrays.asList(Line.split(","));
				}
}				else {if (i%4==2) {{
					String Line = (String)LinesInFile.get(i);
					ColorList = Arrays.asList(Line.split(","));
				}
}				else {if (i%4==3) {{
					String Line = (String)LinesInFile.get(i);
					String[] temp = Line.split(" ");
					EdgeList = Arrays.asList(temp);
					List Edges = new ArrayList();
					for (int j = 0; j<EdgeList.size(); ++j){
						String p = (String)EdgeList.get(j);
						String[] splitp = p.split(",");
						Edges.add(splitp);
					}
					Partitions p = ((Partitions)new Partitions(this).construct(a, NodeList, ColorList, Edges));
					Actors.add(p);
				}
}}}}			}
			List answer = new ArrayList();
			List tokens = new ArrayList();
			{
				Token token_2_0 = new Token();
				// join block
				token_2_0.setJoinDirector();
				for (int i = 0; i<Actors.size(); ++i){
					Partitions aAtI = (Partitions)Actors.get(i);
					{
						// aAtI<-computePartA_better()
						{
							Object _arguments[] = {  };
							Message message = new Message( self, aAtI, "computePartA_better", _arguments, null, token_2_0 );
							__messages.add( message );
						}
					}
				}
				addJoinToken(token_2_0);
				// merge(token)
				{
					Object _arguments[] = { token_2_0 };
					Message message = new Message( self, self, "merge", _arguments, token_2_0, null );
					__messages.add( message );
				}
			}
		}
	}
}