package concurrent;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import java.io.*;
import java.util.*;

public class Partitions extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		RunTime.receivedMessage();
		Partitions instance = (Partitions)new Partitions(uan, ual,null).construct();
		gc.WeakReference instanceRef=new gc.WeakReference(uan,ual);
		{
			Object[] _arguments = { args };

			//preAct() for local actor creation
			//act() for remote actor creation
			if (ual != null && !ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {instance.send( new Message(instanceRef, instanceRef, "act", _arguments, false) );}
			else {instance.send( new Message(instanceRef, instanceRef, "preAct", _arguments, false) );}
		}
		RunTime.finishedProcessingMessage();
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new Partitions(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return Partitions.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new Partitions(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return Partitions.getReferenceByLocation(new UAL(ual)); }
	public Partitions(boolean o, UAN __uan)	{ super(false,__uan); }
	public Partitions(boolean o, UAL __ual)	{ super(false,__ual); }
	public Partitions(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null, sourceActor); }
	public Partitions(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual, sourceActor); }
	public Partitions(UniversalActor.State sourceActor)		{ this(null, null, sourceActor);  }
	public Partitions()		{  }
	public Partitions(UAN __uan, UAL __ual, Object obj) {
		//decide the type of sourceActor
		//if obj is null, the actor must be the startup actor.
		//if obj is an actorReference, this actor is created by a remote actor

		if (obj instanceof UniversalActor.State || obj==null) {
			  UniversalActor.State sourceActor;
			  if (obj!=null) { sourceActor=(UniversalActor.State) obj;}
			  else {sourceActor=null;}

			  //remote creation message sent to a remote system service.
			  if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			    WeakReference sourceRef;
			    if (sourceActor!=null && sourceActor.getUAL() != null) {sourceRef = new WeakReference(sourceActor.getUAN(),sourceActor.getUAL());}
			    else {sourceRef = null;}
			    if (sourceActor != null) {
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual!=null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());
			      activateGC();
			    }
			    createRemotely(__uan, __ual, "concurrent.Partitions", sourceRef);
			  }

			  // local creation
			  else {
			    State state = new State(__uan, __ual);

			    //assume the reference is weak
			    muteGC();

			    //the source actor is  the startup actor
			    if (sourceActor == null) {
			      state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			    }

			    //the souce actor is a normal actor
			    else if (sourceActor instanceof UniversalActor.State) {

			      // this reference is part of garbage collection
			      activateGC();

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());

			      /* Garbage collection registration:
			       * register 'this reference' in sourceActor's forward list @
			       * register 'this reference' in the forward acquaintance's inverse list
			       */
			      String inverseRefString=null;
			      if (sourceActor.getUAN()!=null) {inverseRefString=sourceActor.getUAN().toString();}
			      else if (sourceActor.getUAL()!=null) {inverseRefString=sourceActor.getUAL().toString();}
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual != null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}
			      else {sourceActor.getActorMemory().getForwardList().putReference(state.getUAL());}

			      //put the inverse reference information in the actormemory
			      if (inverseRefString!=null) state.getActorMemory().getInverseList().putInverseReference(inverseRefString);
			    }
			    state.updateSelf(this);
			    ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			    if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
			  }
		}

		//creation invoked by a remote message
		else if (obj instanceof ActorReference) {
			  ActorReference sourceRef= (ActorReference) obj;
			  State state = new State(__uan, __ual);
			  muteGC();
			  state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			  if (sourceRef.getUAN() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAN());}
			  else if (sourceRef.getUAL() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAL());}
			  state.updateSelf(this);
			  ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(),state);
			  if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct (Integer a, List NodeList, List ColorList, List EdgeList) {
		Object[] __arguments = { a, NodeList, ColorList, EdgeList };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State {
		public Partitions self;
		public void updateSelf(ActorReference actorReference) {
			((Partitions)actorReference).setUAL(getUAL());
			((Partitions)actorReference).setUAN(getUAN());
			self = new Partitions(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.activateGC();
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "concurrent.Partitions$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		Integer ActorNum;
		Map color_to_node = new HashMap();
		Map edge_to_node = new HashMap();
		Set internal_node = new HashSet();
		Set All_colors = new HashSet();
		Map influential = new HashMap();
		void construct(Integer a, List NodeList, List ColorList, List EdgeList){
			this.ActorNum = a;
			for (int i = 0; i<NodeList.size(); i++){
				String name = (String)NodeList.get(i);
				int n = Integer.parseInt(name);
				internal_node.add(n);
				String color = (String)ColorList.get(i);
				if (!color_to_node.containsKey(color)) {{
					All_colors.add(color);
					List l = new ArrayList();
					l.add(n);
					color_to_node.put(color, l);
				}
}				else {{
					List l = (List)color_to_node.get(color);
					l.add(n);
					color_to_node.put(color, l);
				}
}			}
			for (int i = 0; i<EdgeList.size(); i++){
				String[] pair = (String[])EdgeList.get(i);
				String s = pair[0];
				String e = pair[1];
				int start = Integer.parseInt(s);
				int end = Integer.parseInt(e);
				if (!edge_to_node.containsKey(start)) {{
					List l = new ArrayList();
					l.add(end);
					edge_to_node.put(start, l);
				}
}				else {{
					List l = (List)edge_to_node.get(start);
					l.add(end);
					edge_to_node.put(start, l);
				}
}				if (!edge_to_node.containsKey(end)) {{
					List l = new ArrayList();
					l.add(start);
					edge_to_node.put(end, l);
				}
}				else {{
					List l = (List)edge_to_node.get(end);
					l.add(start);
					edge_to_node.put(end, l);
				}
}			}
			Iterator it = internal_node.iterator();
						while (it.hasNext()) {
				int deg = 0;
				int n = (int)it.next();
				if (edge_to_node.containsKey(n)) {{
					List t = (List)edge_to_node.get(n);
					deg += t.size();
				}
}				influential.put(n, deg);
			}
		}
		public List computePartA() {
			List ret = new ArrayList();
			Iterator itr = All_colors.iterator();
			while (itr.hasNext()) {
				List info = new ArrayList();
				int deg = 0;
				String c = (String)itr.next();
				List temp = (List)color_to_node.get(c);
				int count = temp.size();
				for (int k = 0; k<count; k++){
					int node = (int)temp.get(k);
					List t = (List)edge_to_node.get(node);
					int num = t.size();
					deg += num;
				}
				info.add(c);
				info.add(count);
				info.add(deg);
				{
					// standardOutput<-println(c+", "+count+", "+deg)
					{
						Object _arguments[] = { c+", "+count+", "+deg };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				ret.add(info);
			}
			{
				// standardOutput<-println(ActorNum)
				{
					Object _arguments[] = { ActorNum };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
			return ret;
		}
		public List computePartA_better() {
			List ret = new ArrayList();
			Map color_to_count = new HashMap();
			Map color_to_degree = new HashMap();
			Iterator itr = All_colors.iterator();
			while (itr.hasNext()) {
				int deg = 0;
				String c = (String)itr.next();
				List temp = (List)color_to_node.get(c);
				int count = temp.size();
				for (int k = 0; k<count; k++){
					int node = (int)temp.get(k);
					List t = (List)edge_to_node.get(node);
					int num = t.size();
					deg += num;
				}
				color_to_count.put(c, count);
				color_to_degree.put(c, deg);
				{
					// standardOutput<-println(c+", "+count+", "+deg)
					{
						Object _arguments[] = { c+", "+count+", "+deg };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
			ret.add(color_to_count);
			ret.add(color_to_degree);
			{
				// standardOutput<-println("success")
				{
					Object _arguments[] = { "success" };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
			return ret;
		}
		public List CalcMostInfluential() {
			List ret = new ArrayList();
			int max_degree = 0;
			List max_degree_nodes = new ArrayList();
			Set nodes = (Set)influential.keySet();
			Iterator itr1 = nodes.iterator();
			while (itr1.hasNext()) {
				int node = (int)itr1.next();
				int degree = (int)influential.get(node);
				if (degree>max_degree) {{
					max_degree = degree;
					max_degree_nodes.clear();
					max_degree_nodes.add(node);
				}
}				else {if (degree==max_degree) {{
					max_degree_nodes.add(node);
				}
}}			}
			ret.add(max_degree);
			ret.add(max_degree_nodes);
			return ret;
		}
		public Set getExternal() {
			Set external_nodes = new HashSet();
			Iterator itr = external_nodes.iterator();
			while (itr.hasNext()) {
				List neighbors = (List)itr.next();
				for (int i = 0; i<neighbors.size(); i++){
					int node = (int)neighbors.get(i);
					if (!internal_node.contains(node)) {{
						external_nodes.add(node);
					}
}				}
			}
			return external_nodes;
		}
	}
}